const MESSAGE_TYPES = {
    NEW_MESSAGE: "NEW_MESSAGE",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    ACKNOWLEDGMENT: "ACKNOWLEDGMENT",
    ERROR: "ERROR"
}




module.exports = {
    MESSAGE_TYPES
};